### ISSUE TITLE
File nomenclature keep one standard

### ISSUE THREAD

**Issue by krolow** [sqlectron/sqlectron#2]
So far we are using different standards to give the name for files for example:

**actions**
- [databases.js](https://github.com/sqlectron/sqlectron/blob/47e3074d6f830ccd3544a864b99e372a9bf7a1a4/src/actions/databases.js)

**constants**
- [ActionTypes](https://github.com/sqlectron/sqlectron/blob/47e3074d6f830ccd3544a864b99e372a9bf7a1a4/src/constants/ActionTypes.js)

etc..

Some files start in **Uppercase**, others in **lowercase**, what about we keep one standard between them?

- A. myFile.jsx
- B. my-file.jsx
- C. MyFile.jsx

Same happens with the name given for the files, some keep one suffix others not like:

- [DatabaseListController.js](https://github.com/sqlectron/sqlectron/blob/47e3074d6f830ccd3544a864b99e372a9bf7a1a4/src/controllers/DatabaseListController.jsx)

and...

- [databases.js](https://github.com/sqlectron/sqlectron/blob/47e3074d6f830ccd3544a864b99e372a9bf7a1a4/src/reducers/databases.js)

I'd say we can also keep some standard, or use a suffix like ```DatabaseReducer.js``` ```DatabaseListController.js``` or does not use the suffix...

What should we use/follow guys? @maxcnunes @esnunes

**Comment by krolow** [comment]
To answer as well, and give my insight, i'd say for use use:

use ```"my-file.js"``` and use suffix ```"database-reducer.js"```...

For the usage of **"-"** i do not have one reason only because its the most common in use when we talk about unix style...

For the usage of **suffix** i'd say it would be good when we are in or editor/ide to filter the files that we want to open like in atom, sublime, we would be able to type "controller" in the file search and it would list all controller files that we have in the app...

Like i said its more personal the choice, its just important to keep one standard...

**Comment by maxcnunes** [comment]
I have seen many open source projects nowadays with react using camel case for filenames. But I personally don't like it. I prefer using the unix style for any filename.

Related to suffix I think they are redundant since the folder name already has the suffix value. You can still use the fuzzy search from sublime and atom to find the file. Just have to include in the search the folder name and filename. But in case you prefer using the suffix I have no problems with that.

**Comment by esnunes** [comment]
I like option B `my-file.jsx` using lowercase only. I agree with Max regarding the usage of folder name to identify a section. However, as Max mentioned, in case you prefer using the suffix I have no problems with that.

**Comment by krolow** [comment]
for me no problem at all to not have the suffix too, it's just personal preference for usage in (rails, cakephp), but lets keep one standard of not use than...
